"use strict";

const VERSION="1.0.0",SCHEMA_VERSION=3,DB_NAME="minimal-daily-os",DB_VERSION=2,MAX_PRIORITIES=10,MAX_LAUNCHERS=30;
const SAFE_PROTOCOLS=new Set(["https:","http:","tel:","sms:","mailto:","facetime:","facetime-audio:","shortcuts:","maps:","music:","spotify:"]);
const ACCENTS={mint:["#9cffc8","156,255,200"],ice:["#8fdcff","143,220,255"],amber:["#ffc56e","255,197,110"],violet:["#c9a7ff","201,167,255"],coral:["#ff9b8e","255,155,142"],blue:["#87aaff","135,170,255"]};
const DEFAULT_LAUNCHERS=[
 {id:"calls",name:"Calls",url:"tel:",symbol:"C",color:"#9cffc8",pinned:true,order:0},
 {id:"messages",name:"Messages",url:"sms:",symbol:"M",color:"#8fdcff",pinned:true,order:1},
 {id:"maps",name:"Maps",url:"https://maps.apple.com/",symbol:"↗",color:"#ffc56e",pinned:false,order:2},
 {id:"music",name:"Music",url:"https://music.apple.com/",symbol:"♪",color:"#c9a7ff",pinned:false,order:3}
];
const $=id=>document.getElementById(id);let db=null,fallback=false,config,days=[],activeDate=dateKey(),editable=true,dialogMode="",conclusionTimer,toastTimer,focusInterval;const scoreBaselines=new Map();

document.addEventListener("DOMContentLoaded",init);
async function init(){bind();await openDatabase();await loadData();await migrateLegacy();await ensureToday();renderAll();tick();syncFocusTimer();setInterval(tick,1000);focusInterval=setInterval(syncFocusTimer,500);addEventListener("online",renderOnline);addEventListener("offline",renderOnline);addEventListener("focus",resumeForeground);addEventListener("pageshow",resumeForeground);document.addEventListener("visibilitychange",()=>{if(!document.hidden)resumeForeground();});registerServiceWorker();await checkReminder();}

function bind(){
 $("item-form").addEventListener("click",e=>{if(e.target.closest('button[value="cancel"]')){e.preventDefault();$("item-dialog").close();}});
 document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));
 $("priority-form").addEventListener("submit",e=>addPriority(e,false));$("tomorrow-form").addEventListener("submit",e=>addPriority(e,true));
 $("priority-list").addEventListener("click",itemAction);$("tomorrow-list").addEventListener("click",itemAction);$("moves-list").addEventListener("click",itemAction);$("move-settings").addEventListener("click",itemAction);$("move-form").addEventListener("submit",addMove);
 $("launcher-grid").addEventListener("click",launcherAction);$("add-launcher").addEventListener("click",()=>openItemDialog("launcher"));
 $("item-form").addEventListener("submit",saveDialogItem);$("item-dialog").addEventListener("close",()=>{$("dialog-error").textContent="";});
 $("conclusion").addEventListener("input",queueConclusion);$("edit-day-button").addEventListener("click",()=>{editable=true;renderToday();});
 $("history-year").addEventListener("change",renderHistory);$("history-list").addEventListener("click",e=>{const b=e.target.closest("[data-date]");if(b)openHistoricalDay(b.dataset.date);});
 $("profile-form").addEventListener("submit",saveProfile);$("accent-options").addEventListener("click",e=>{const b=e.target.closest("[data-accent]");if(b){config.accent=b.dataset.accent;applyAccent();renderSettings();}});
 $("export-json").addEventListener("click",exportJson);$("export-readable").addEventListener("click",exportReadable);$("import-json").addEventListener("change",importJson);
 $("clear-data").addEventListener("click",()=>{$("clear-confirm").hidden=false;$("clear-phrase").focus();});$("cancel-clear").addEventListener("click",()=>{$("clear-confirm").hidden=true;});$("confirm-clear").addEventListener("click",clearAll);
 $("share-feedback").addEventListener("click",shareFeedback);$("rollover-dialog").addEventListener("close",finishRollover);$("save-prompts").addEventListener("click",savePrompts);$("dismiss-reminder").addEventListener("click",dismissReminder);$("active-focus-bar").addEventListener("click",showFocusLayer);document.querySelectorAll("[data-focus-minutes]").forEach(b=>b.addEventListener("click",()=>setFocusDuration(Number(b.dataset.focusMinutes))));$("set-custom-focus").addEventListener("click",()=>setFocusDuration(Number($("custom-focus-minutes").value)));$("focus-start").addEventListener("click",startFocusTimer);$("focus-pause").addEventListener("click",pauseFocusTimer);$("focus-reset").addEventListener("click",resetFocusTimer);$("focus-back").addEventListener("click",backToToday);$("focus-break").addEventListener("click",startFocusBreak);$("focus-mark-done").addEventListener("click",markFocusedItemDone);
}

function defaultConfig(){return{key:"main",version:VERSION,name:"",initials:"",locationLabel:"",accent:"mint",milestoneEnabled:true,reminder:{enabled:false,time:"18:00"},focusTimer:null,moves:[],launchers:DEFAULT_LAUNCHERS,updatedAt:Date.now(),lastDate:null,migrated:false};}
function blankDay(date,moves=config.moves){return{date,priorities:[],planned:[],moves:moves.filter(m=>m.enabled!==false).map(m=>({id:m.id,label:m.label,status:"pending",enabled:true,order:m.order})),focusSessions:[],conclusion:"",milestoneCelebrated:false,reminderShown:false,reminderDismissed:false,updatedAt:Date.now()};}
function openDatabase(){return new Promise(resolve=>{if(!("indexedDB" in window)){fallback=true;resolve();return;}const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains("config"))d.createObjectStore("config",{keyPath:"key"});if(!d.objectStoreNames.contains("days"))d.createObjectStore("days",{keyPath:"date"});};r.onsuccess=()=>{db=r.result;db.onversionchange=()=>db.close();resolve();};r.onerror=()=>{fallback=true;resolve();};});}
async function loadData(){try{if(fallback){const raw=JSON.parse(localStorage.getItem("minimal.2.2.fallback")||"null");config=sanitizeConfig(raw?.config);days=Array.isArray(raw?.days)?raw.days.map(sanitizeDay).filter(Boolean):[];}else{config=sanitizeConfig(await idbGet("config","main"));days=(await idbAll("days")).map(sanitizeDay).filter(Boolean);}}catch{fallback=true;config=defaultConfig();days=[];showToast("Local database unavailable. Using temporary local storage.");}config=config||defaultConfig();applyAccent();}
function idbGet(store,key){return new Promise((res,rej)=>{const r=db.transaction(store).objectStore(store).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function idbAll(store){return new Promise((res,rej)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function idbPut(store,value){return new Promise((res,rej)=>{const r=db.transaction(store,"readwrite").objectStore(store).put(value);r.onsuccess=()=>res();r.onerror=()=>rej(r.error);});}
async function persistConfig(){config.updatedAt=Date.now();if(fallback)return saveFallback();try{await idbPut("config",config);}catch{fallback=true;saveFallback();}}
async function persistDay(day){day.updatedAt=Date.now();const i=days.findIndex(d=>d.date===day.date);if(i<0)days.push(day);else days[i]=day;if(fallback)return saveFallback();try{await idbPut("days",day);}catch{fallback=true;saveFallback();}}
function saveFallback(){try{localStorage.setItem("minimal.2.2.fallback",JSON.stringify({config,days}));}catch{showToast("Changes could not be saved. Export a backup now.");}}

async function migrateLegacy(){if(config.migrated)return;const keys=["minimal.private-beta.2.1","minimal.phone.state.v2","minimal.phone.state"];for(const key of keys){try{const old=JSON.parse(localStorage.getItem(key)||"null");if(!old)continue;const src=old.state||old;if(src.profile){config.name=text(src.profile.name,40);config.accent=ACCENTS[src.profile.accent]?src.profile.accent:config.accent;}if(Array.isArray(src.apps)){config.launchers=src.apps.slice(0,MAX_LAUNCHERS).map((a,i)=>({id:safeId(a.id,"app"),name:text(a.name,40)||"App",url:normalizeUrl(a.target||a.url)||"https://example.com/",symbol:text(a.symbol,3)||text(a.name,1).toUpperCase(),color:validColor(a.color)?a.color:"#9cffc8",pinned:Boolean(a.pinned),order:i}));}const today=getDay(dateKey())||blankDay(dateKey());if(Array.isArray(src.tasks)&&!today.priorities.length)today.priorities=src.tasks.slice(0,10).map((t,i)=>({id:safeId(t.id,"priority"),text:text(t.text||t.title,140),status:t.done||t.completed?"done":"pending",order:i}));if(text(src.priority,140)&&today.priorities.length<10)today.priorities.unshift({id:uid("priority"),text:text(src.priority,140),status:"pending",order:0});await persistDay(today);break;}catch{/* Ignore corrupt legacy state. */}}config.migrated=true;await persistConfig();}
async function ensureToday(){const today=dateKey();activeDate=today;let day=getDay(today);if(!day){day=blankDay(today);const yesterday=latestDayBefore(today);if(yesterday?.planned?.length)day.priorities=yesterday.planned.slice(0,10).map((p,i)=>({id:uid("priority"),text:p.text,status:"pending",order:i}));await persistDay(day);}const previous=latestDayBefore(today);config.lastDate=today;await persistConfig();if(previous&&previous.date!==today&&previous.priorities.some(p=>p.status!=="done")&&!previous.rolloverResolved){$("rollover-message").textContent=`${previous.priorities.filter(p=>p.status!=="done").length} unfinished item(s) remain from ${formatDate(previous.date)}. Planned items are already in today.`;$("rollover-dialog").dataset.from=previous.date;$("rollover-dialog").showModal();}}
async function finishRollover(){const choice=$("rollover-dialog").returnValue;if(!["carry","archive","delete"].includes(choice))return;const old=getDay($("rollover-dialog").dataset.from),today=getDay(dateKey());if(!old||!today)return;const unfinished=old.priorities.filter(p=>p.status!=="done");if(choice==="carry"){const existing=new Set(today.priorities.map(p=>p.text.toLowerCase()));for(const p of unfinished){if(today.priorities.length>=10)break;if(!existing.has(p.text.toLowerCase()))today.priorities.push({id:uid("priority"),text:p.text,status:"pending",order:today.priorities.length});}}if(choice==="delete")old.priorities=old.priorities.filter(p=>p.status==="done");old.rolloverResolved=choice;await Promise.all([persistDay(old),persistDay(today)]);renderAll();showToast(choice==="carry"?"Unfinished priorities carried forward.":choice==="delete"?"Unfinished priorities deleted.":"Unfinished priorities archived incomplete.");}

function renderAll(){renderOnline();renderToday();renderLauncher();renderHistoryYears();renderHistory();renderSettings();renderFocusTimer();$("move-form").querySelector("button").disabled=false;}
function currentDay(){return getDay(activeDate)||blankDay(activeDate);}
function renderToday(){const day=currentDay(),isToday=activeDate===dateKey(),visibleMoves=day.moves.filter(m=>m.enabled!==false);editable=isToday?true:editable;$("today-title").textContent=isToday?(config.name?`Today, ${config.name}`:"Today"):"Daily record";const dt=parseDate(activeDate);$("today-weekday").textContent=dt.toLocaleDateString(undefined,{weekday:"long"}).toUpperCase();$("today-date").textContent=dt.toLocaleDateString(undefined,{year:"numeric",month:"long",day:"numeric"});$("readonly-banner").hidden=isToday||editable;$("edit-day-button").hidden=isToday||editable;renderItems($("priority-list"),day.priorities,"priority",editable);$("priority-empty").hidden=day.priorities.length>0;$("priority-count").textContent=`${day.priorities.length} / 10`;renderItems($("moves-list"),visibleMoves,"move",editable);$("moves-empty").hidden=visibleMoves.length>0;$("moves-count").textContent=`${visibleMoves.length} ENABLED`;renderItems($("tomorrow-list"),day.planned,"tomorrow",editable);$("tomorrow-empty").hidden=day.planned.length>0;$("tomorrow-count").textContent=`${day.planned.length} / 10`;$("conclusion").value=day.conclusion;$("conclusion").disabled=!editable;$("priority-form").hidden=!editable;$("tomorrow-form").hidden=!editable;renderScores(day);}
function renderItems(root,items,type,canEdit){root.replaceChildren();[...items].sort((a,b)=>a.order-b.order).forEach((item,index)=>{const status=validStatus(item.status),name=item.text||item.label,li=document.createElement("li");li.className=`item ${status}`;li.dataset.id=item.id;li.dataset.type=type;if(type!=="tomorrow"){const controls=document.createElement("span");controls.className="status-controls";const done=actionButton("✓","status-done",status==="done"?`Return ${name} to pending`:`Mark ${name} complete`),skipped=actionButton("×","status-skipped",status==="skipped"?`Return ${name} to pending`:`Mark ${name} skipped`);done.className="status-button done-control";skipped.className="status-button skip-control";done.disabled=skipped.disabled=!canEdit;done.setAttribute("aria-pressed",String(status==="done"));skipped.setAttribute("aria-pressed",String(status==="skipped"));controls.append(done,skipped);li.append(controls);}else li.append(document.createElement("span"));const content=document.createElement("span"),label=document.createElement("span");content.className="item-content";label.className="item-text";label.textContent=name;content.append(label);const summary=focusSummary(currentDay(),type,item.id);if(summary){const meta=document.createElement("small");meta.className="focus-summary";meta.textContent=summary;content.append(meta);}li.append(content);if(canEdit){const actions=document.createElement("span");actions.className="item-actions";if(index>0)actions.append(actionButton("↑","up","Move up"));if(index<items.length-1)actions.append(actionButton("↓","down","Move down"));if(activeDate===dateKey()&&(type==="priority"||type==="move"))actions.append(actionButton("Focus","focus",`Focus on ${name}`));if(type!=="move")actions.append(actionButton("Edit","edit","Edit"),actionButton("Delete","delete","Delete"));li.append(actions);}root.append(li);});}
function actionButton(label,action,aria){const b=document.createElement("button");b.type="button";b.className="icon-action";b.dataset.action=action;b.textContent=label;b.setAttribute("aria-label",aria);return b;}
async function itemAction(e){const button=e.target.closest("[data-action]"),li=e.target.closest("[data-id]");if(!button||!li||(!editable&&e.currentTarget.id!=="move-settings"))return;const day=currentDay(),type=li.dataset.type,isMoveSettings=e.currentTarget.id==="move-settings",list=type==="priority"?day.priorities:type==="tomorrow"?day.planned:isMoveSettings?config.moves:day.moves;const index=list.findIndex(i=>i.id===li.dataset.id);if(index<0)return;const action=button.dataset.action;if(action==="focus")return openFocus(day.date,type,list[index]);if(action==="rename-move")return openItemDialog("moveconfig",list[index]);if(isMoveSettings&&action==="toggle-enabled")list[index].enabled=list[index].enabled===false;else if(action==="status-done")list[index].status=list[index].status==="done"?"pending":"done";else if(action==="status-skipped")list[index].status=list[index].status==="skipped"?"pending":"skipped";else if(action==="delete")list.splice(index,1);else if(action==="up"&&index>0)[list[index-1],list[index]]=[list[index],list[index-1]];else if(action==="down"&&index<list.length-1)[list[index+1],list[index]]=[list[index],list[index+1]];else if(action==="edit")return openItemDialog(type,list[index]);list.forEach((v,i)=>v.order=i);if(isMoveSettings){await syncCurrentDayMoves();await persistConfig();}else await persistDay(day);renderAll();await checkReminder();}

async function syncCurrentDayMoves(){const day=getDay(dateKey());if(!day)return;const configured=new Set(config.moves.map(m=>m.id));day.moves=day.moves.filter(m=>configured.has(m.id));config.moves.forEach((move,index)=>{let snapshot=day.moves.find(m=>m.id===move.id);if(!snapshot){snapshot={id:move.id,label:move.label,status:"pending",enabled:move.enabled!==false,order:index};day.moves.push(snapshot);}snapshot.label=move.label;snapshot.enabled=move.enabled!==false;snapshot.order=index;});await persistDay(day);}

async function addMove(e){e.preventDefault();const input=$("move-input"),label=text(input.value,80),message=$("move-form-message");message.textContent="";if(!label)return;if(config.moves.length>=10){message.textContent="You can configure up to 10 Small Moves. Delete one before adding another.";return;}if(config.moves.some(m=>m.label.toLowerCase()===label.toLowerCase())){message.textContent="That Small Move already exists.";return;}config.moves.push({id:uid("move"),label,enabled:true,order:config.moves.length});input.value="";await syncCurrentDayMoves();await persistConfig();renderAll();message.textContent="Small Move added.";}
async function addPriority(e,tomorrow){e.preventDefault();if(!editable)return;const input=$(tomorrow?"tomorrow-input":"priority-input"),value=text(input.value,140),day=currentDay(),list=tomorrow?day.planned:day.priorities;if(!value)return;if(list.length>=MAX_PRIORITIES)return showToast("The daily limit is 10 priorities.");if(list.some(p=>p.text.toLowerCase()===value.toLowerCase()))return showToast("That priority is already listed.");list.push({id:uid(tomorrow?"planned":"priority"),text:value,status:"pending",order:list.length});input.value="";await persistDay(day);renderToday();}
function renderScores(day){const enabledMoves=day.moves.filter(m=>m.enabled!==false),p=score(day.priorities),m=score(enabledMoves),all=score([...day.priorities,...enabledMoves]),previous=scoreBaselines.get(day.date);setScore("priority-score",p);setScore("moves-score",m);setScore("overall-score",all);$("target-status").textContent=all.percent===null?"Not measured":all.percent>=80?"Target reached":"Continue tomorrow";document.querySelector(".target-card").classList.toggle("reached",all.percent!==null&&all.percent>=80);scoreBaselines.set(day.date,all.percent??0);if(day.date===dateKey()&&previous!==undefined&&previous<80&&all.percent!==null&&all.percent>=80&&config.milestoneEnabled&&!day.milestoneCelebrated){day.milestoneCelebrated=true;persistDay(day);showToast("80% secured — the essential work is done.",5000);}}
function score(items){const tracked=items.filter(i=>i.enabled!==false),total=tracked.length,done=tracked.filter(i=>validStatus(i.status)==="done").length;return{done,total,percent:total?Math.round(done/total*100):null};}function setScore(id,s){$(id).textContent=s.percent===null?"Not measured":`${s.percent}%`;}
function queueConclusion(){if(!editable)return;$("conclusion-status").textContent="Saving…";clearTimeout(conclusionTimer);conclusionTimer=setTimeout(async()=>{const day=currentDay();day.conclusion=text($("conclusion").value,500,true);await persistDay(day);$("conclusion-status").textContent="Saved locally";renderHistory();},550);}

function renderLauncher(){const root=$("launcher-grid");root.replaceChildren();const sorted=[...config.launchers].sort((a,b)=>Number(b.pinned)-Number(a.pinned)||a.order-b.order);sorted.forEach((app,index)=>{const wrap=document.createElement("div");const b=document.createElement("button");b.type="button";b.className=`launcher${app.pinned?" pinned":""}`;b.style.setProperty("--launcher-accent",app.color);b.dataset.action="open";b.dataset.id=app.id;const symbol=document.createElement("span");symbol.className="launcher-symbol";symbol.textContent=app.symbol||app.name[0];const name=document.createElement("strong");name.textContent=app.name;b.append(symbol,name);const manage=document.createElement("div");manage.className="launcher-manage";if(index>0)manage.append(actionButton("↑","launcher-up","Move up"));if(index<sorted.length-1)manage.append(actionButton("↓","launcher-down","Move down"));manage.append(actionButton("Edit","launcher-edit","Edit launcher"),actionButton("Delete","launcher-delete","Delete launcher"));manage.dataset.id=app.id;wrap.append(b,manage);root.append(wrap);});$("launcher-empty").hidden=config.launchers.length>0;$("add-launcher").disabled=config.launchers.length>=MAX_LAUNCHERS;}
async function launcherAction(e){const target=e.target.closest("[data-action]");if(!target)return;const id=(target.closest("[data-id]")||{}).dataset?.id,app=config.launchers.find(a=>a.id===id),action=target.dataset.action;if(!app)return;if(action==="open"){const url=normalizeUrl(app.url);if(!url)return showToast("This launcher has an invalid destination.");let returned=false;const onReturn=()=>{returned=true;document.removeEventListener("visibilitychange",onReturn);};document.addEventListener("visibilitychange",onReturn);location.href=url;setTimeout(()=>{if(!returned&&!document.hidden)showToast("iOS may not support this deep link. Edit it or use an HTTPS/Shortcuts link.");},1400);return;}if(action==="launcher-edit")return openItemDialog("launcher",app);if(action==="launcher-delete")config.launchers=config.launchers.filter(a=>a.id!==id);else{const sorted=[...config.launchers].sort((a,b)=>Number(b.pinned)-Number(a.pinned)||a.order-b.order),i=sorted.findIndex(a=>a.id===id),swap=action==="launcher-up"?i-1:i+1;if(swap>=0&&swap<sorted.length){[sorted[i],sorted[swap]]=[sorted[swap],sorted[i]];sorted.forEach((a,n)=>a.order=n);}}await persistConfig();renderLauncher();}
function openItemDialog(mode,item){dialogMode=mode;$("item-id").value=item?.id||"";$("item-text").value=item?.text||item?.label||item?.name||"";$("launcher-fields").hidden=mode!=="launcher";$("item-dialog-title").textContent=mode==="moveconfig"?"Rename Small Move":item?`Edit ${mode}`:`Add ${mode}`;$("item-label").firstChild.textContent=mode==="launcher"?"Name":mode==="moveconfig"?"Label":"Text";if(mode==="launcher"){$("launcher-url").value=item?.url||"";$("launcher-symbol").value=item?.symbol||"";$("launcher-color").value=validColor(item?.color)?item.color:"#9cffc8";$("launcher-pinned").checked=Boolean(item?.pinned);}$("item-dialog").showModal();$("item-text").focus();}
async function saveDialogItem(e){e.preventDefault();const value=text($("item-text").value,dialogMode==="launcher"?40:140),id=$("item-id").value;if(!value)return;if(dialogMode==="launcher"){const url=normalizeUrl($("launcher-url").value);if(!url){$("dialog-error").textContent="Use HTTPS, HTTP on localhost, or a supported iPhone deep link. JavaScript and data URLs are blocked.";return;}if(!id&&config.launchers.length>=30)return showToast("Launcher limit reached (30).");const app=id?config.launchers.find(a=>a.id===id):null,data={id:app?.id||uid("app"),name:value,url,symbol:text($("launcher-symbol").value,3)||value[0].toUpperCase(),color:$("launcher-color").value,pinned:$("launcher-pinned").checked,order:app?.order??config.launchers.length};if(app)Object.assign(app,data);else config.launchers.push(data);await persistConfig();renderLauncher();}else if(dialogMode==="moveconfig"){const move=config.moves.find(m=>m.id===id);if(move)move.label=text(value,80);const today=getDay(dateKey()),snapshot=today?.moves.find(m=>m.id===id);if(snapshot){snapshot.label=move.label;await persistDay(today);}await persistConfig();renderAll();}else{const day=currentDay(),list=dialogMode==="priority"?day.priorities:day.planned,item=list.find(i=>i.id===id);if(item)item.text=value;await persistDay(day);renderToday();}$("item-dialog").close();}

function renderSettings(){$("display-name").value=config.name;$("initials").value=config.initials;$("location-label").value=config.locationLabel;$("milestone-enabled").checked=config.milestoneEnabled;$("reminder-enabled").checked=config.reminder.enabled;$("reminder-time").value=config.reminder.time;const accents=$("accent-options");accents.replaceChildren();Object.entries(ACCENTS).forEach(([name,[color]])=>{const b=document.createElement("button");b.type="button";b.className=`accent-choice${config.accent===name?" selected":""}`;b.dataset.accent=name;b.style.setProperty("--swatch",color);b.setAttribute("aria-label",`${name} accent`);b.setAttribute("aria-pressed",String(config.accent===name));accents.append(b);});const root=$("move-settings");root.replaceChildren();config.moves.forEach((m,i)=>{const li=document.createElement("li");li.className=`item configured-move${m.enabled===false?" disabled":""}`;li.dataset.id=m.id;li.dataset.type="move";const state=document.createElement("span");state.className="move-state";state.textContent=m.enabled===false?"OFF":"ON";const label=document.createElement("span");label.className="item-text";label.textContent=m.label;const actions=document.createElement("span");actions.className="item-actions";if(i)actions.append(actionButton("↑","up","Move up"));if(i<config.moves.length-1)actions.append(actionButton("↓","down","Move down"));actions.append(actionButton("Rename","rename-move","Rename"),actionButton(m.enabled===false?"Enable":"Disable","toggle-enabled",m.enabled===false?"Enable":"Disable"),actionButton("Delete","delete","Delete"));li.append(state,label,actions);root.append(li);});$("move-config-count").textContent=`${config.moves.length} / 10`;$("move-settings-empty").hidden=config.moves.length>0;}
async function saveProfile(e){e.preventDefault();config.name=text($("display-name").value,40);config.initials=text($("initials").value,3).toUpperCase();config.locationLabel=text($("location-label").value,40);await persistConfig();renderAll();showToast("Profile saved.");}

async function savePrompts(){const previous=`${config.reminder.enabled}:${config.reminder.time}`,time=/^([01]\d|2[0-3]):[0-5]\d$/.test($("reminder-time").value)?$("reminder-time").value:"18:00";config.milestoneEnabled=$("milestone-enabled").checked;config.reminder={enabled:$("reminder-enabled").checked,time};if(previous!==`${config.reminder.enabled}:${time}`){const day=getDay(dateKey());if(day){day.reminderShown=false;day.reminderDismissed=false;await persistDay(day);}}await persistConfig();renderSettings();showToast("Daily prompts saved.");await checkReminder();}

function hasDailyActivity(day){return[...day.priorities,...day.moves.filter(m=>m.enabled!==false)].some(item=>validStatus(item.status)!=="pending");}
function reminderDue(now=new Date()){if(!config.reminder.enabled)return false;const day=getDay(dateKey());if(!day||day.reminderShown||day.reminderDismissed||hasDailyActivity(day))return false;const [hour,minute]=config.reminder.time.split(":").map(Number),threshold=new Date(now);threshold.setHours(hour,minute,0,0);return now>=threshold;}
async function checkReminder(){if(!config||document.hidden)return;const day=getDay(dateKey());if(day&&hasDailyActivity(day)){$("reminder-banner").hidden=true;return;}if(!reminderDue())return;day.reminderShown=true;await persistDay(day);$("reminder-banner").hidden=false;}
async function dismissReminder(){const day=getDay(dateKey());$("reminder-banner").hidden=true;if(day){day.reminderDismissed=true;await persistDay(day);}}

function focusSummary(day,type,itemId){const sessions=(day.focusSessions||[]).filter(s=>s.itemType===type&&s.itemId===itemId),minutes=sessions.reduce((n,s)=>n+Math.round(s.plannedDuration/60),0);return sessions.length?`${sessions.length} focus${sessions.length===1?"":"es"} · ${minutes} min`:"";}
async function openFocus(date,itemType,item){const existing=config.focusTimer,label=text(item.text||item.label,140);if(existing&&!existing.acknowledged){showFocusLayer();if(existing.itemId!==item.id)showToast(`Focus is already attached to ${existing.itemLabel}. Reset or finish it first.`);return;}config.focusTimer={date,itemType,itemId:item.id||null,itemLabel:label,duration:1500,remaining:1500,running:false,endAt:null,completed:false,acknowledged:false,sessionRecorded:false,isBreak:false};await persistConfig();showFocusLayer();renderFocusTimer();}
function showFocusLayer(){if(!config.focusTimer)return;$("focus-layer").hidden=false;document.body.classList.add("focus-open");renderFocusTimer();$("focus-start").focus();}
async function backToToday(){const timer=config.focusTimer;if(timer?.completed){timer.acknowledged=true;await persistConfig();}$("focus-layer").hidden=true;document.body.classList.remove("focus-open");activeDate=dateKey();editable=true;showView("today");renderAll();}
async function setFocusDuration(minutes){const timer=config.focusTimer,value=Math.round(Number(minutes));if(!timer||timer.running||timer.completed)return;if(!Number.isFinite(value)||value<1||value>180)return showToast("Choose a duration from 1 to 180 minutes.");timer.duration=value*60;timer.remaining=timer.duration;timer.endAt=null;await persistConfig();renderFocusTimer();}
async function startFocusTimer(){const timer=config.focusTimer;if(!timer||timer.running||timer.completed)return;if(timer.remaining<=0)timer.remaining=timer.duration;timer.running=true;timer.endAt=Date.now()+timer.remaining*1000;await persistConfig();renderFocusTimer();}
async function pauseFocusTimer(){const timer=config.focusTimer;if(!timer||!timer.running||timer.completed)return;timer.remaining=remainingAt(timer,Date.now());timer.running=false;timer.endAt=null;await persistConfig();renderFocusTimer();}
async function resetFocusTimer(){config.focusTimer=null;await persistConfig();$("focus-layer").hidden=true;document.body.classList.remove("focus-open");renderFocusTimer();showToast("Focus timer reset.");}
async function startFocusBreak(){const prior=config.focusTimer;if(!prior?.completed||prior.isBreak)return;config.focusTimer={date:dateKey(),itemType:"break",itemId:null,itemLabel:"5-minute break",duration:300,remaining:300,running:false,endAt:null,completed:false,acknowledged:false,sessionRecorded:true,isBreak:true};await persistConfig();renderFocusTimer();}
async function markFocusedItemDone(){const timer=config.focusTimer;if(!timer?.completed||timer.isBreak)return;const day=getDay(timer.date),list=timer.itemType==="priority"?day?.priorities:day?.moves,item=list?.find(i=>i.id===timer.itemId);if(!item){showToast("The original item is no longer available. The focus session remains saved.");return;}item.status="done";timer.acknowledged=true;await persistDay(day);await persistConfig();renderAll();showToast(`${timer.itemLabel} marked done.`);}
function remainingAt(timer,now=Date.now()){return timer.running&&timer.endAt?Math.max(0,Math.ceil((timer.endAt-now)/1000)):Math.max(0,Math.round(timer.remaining||0));}
async function syncFocusTimer(now=Date.now()){const timer=config?.focusTimer;if(!timer){renderFocusTimer();return;}if(timer.running){const remaining=remainingAt(timer,now);timer.remaining=remaining;if(remaining<=0){const completedAt=timer.endAt||now;timer.running=false;timer.endAt=null;timer.completed=true;if(!timer.isBreak&&!timer.sessionRecorded){timer.sessionRecorded=true;await recordFocusSession(timer,completedAt);}await persistConfig();if(!document.hidden&&navigator.vibrate)try{navigator.vibrate(80);}catch{/* Visual completion remains sufficient. */}}}renderFocusTimer();}
async function recordFocusSession(timer,completedAt){const day=getDay(timer.date);if(!day)return;day.focusSessions=day.focusSessions||[];day.focusSessions.push({id:uid("focus"),date:timer.date,itemType:timer.itemType,itemId:timer.itemId,itemLabel:timer.itemLabel,plannedDuration:timer.duration,completedAt:new Date(completedAt).toISOString()});await persistDay(day);renderAll();}
function renderFocusTimer(){const timer=config?.focusTimer,bar=$("active-focus-bar");if(!timer){bar.hidden=true;$("focus-timer").textContent="25:00";return;}const remaining=remainingAt(timer),display=formatTimer(remaining);$("focus-title").textContent=timer.itemLabel;$("focus-context").textContent=timer.isBreak?"Break":"Attached to today’s "+(timer.itemType==="priority"?"priority":"Small Move");$("focus-timer").textContent=display;$("focus-status").textContent=timer.completed?(timer.isBreak?"Break complete":"Focus complete"):timer.running?"Running":remaining<timer.duration?"Paused":"Ready";$("focus-start").hidden=timer.running||timer.completed;$("focus-start").textContent=remaining<timer.duration?"Resume":"Start";$("focus-pause").hidden=!timer.running||timer.completed;$("duration-choices").hidden=timer.running||timer.completed||timer.isBreak;$("focus-complete-actions").hidden=!timer.completed||timer.isBreak;bar.hidden=timer.acknowledged||(!timer.running&&!timer.completed&&remaining===timer.duration);$("active-focus-label").textContent=`Focus: ${timer.itemLabel}`;$("active-focus-time").textContent=timer.completed?"Complete":display;bar.setAttribute("aria-label",`${timer.itemLabel}, ${timer.completed?"focus complete":display+" remaining"}. Return to Focus.`);}
function formatTimer(seconds){const safe=Math.max(0,Math.round(seconds));return`${String(Math.floor(safe/60)).padStart(2,"0")}:${String(safe%60).padStart(2,"0")}`;}
async function resumeForeground(){await syncFocusTimer();await checkReminder();}
function applyAccent(){const [color,rgb]=ACCENTS[config?.accent]||ACCENTS.mint;document.documentElement.style.setProperty("--accent",color);document.documentElement.style.setProperty("--accent-rgb",rgb);localStorage.setItem("minimal.accent",config?.accent||"mint");}

function renderHistoryYears(){const years=[...new Set(days.map(d=>d.date.slice(0,4)))].sort().reverse(),current=String(new Date().getFullYear());if(!years.includes(current))years.unshift(current);const select=$("history-year"),old=select.value;select.replaceChildren();years.forEach(y=>{const o=document.createElement("option");o.value=y;o.textContent=y;select.append(o);});select.value=years.includes(old)?old:current;}
function renderHistory(){const year=$("history-year").value||String(new Date().getFullYear()),records=days.filter(d=>d.date.startsWith(year)).sort((a,b)=>b.date.localeCompare(a.date));$("history-list").replaceChildren();records.forEach(day=>{const s=score([...day.priorities,...day.moves]),p=score(day.priorities),m=score(day.moves),items=[...day.priorities,...day.moves.filter(x=>x.enabled!==false)],pending=items.filter(x=>validStatus(x.status)==="pending").length,skipped=items.filter(x=>validStatus(x.status)==="skipped").length;const b=document.createElement("button");b.type="button";b.className="history-card";b.dataset.date=day.date;const info=document.createElement("span"),strong=document.createElement("strong"),details=document.createElement("small");strong.textContent=`${parseDate(day.date).toLocaleDateString(undefined,{weekday:"long"})}, ${formatDate(day.date)}`;details.textContent=`Priorities ${p.done}/${p.total} · Moves ${m.done}/${m.total} · ${pending} pending · ${skipped} skipped${day.conclusion?" · Conclusion saved":""}`;info.append(strong,details);const pct=document.createElement("span");pct.className="history-score";pct.textContent=s.percent===null?"—":`${s.percent}%`;b.append(info,pct);$("history-list").append(b);});$("history-empty").hidden=records.length>0;renderYearSummary(records,year);}
function renderYearSummary(records,year){const measured=records.map(d=>score([...d.priorities,...d.moves])).filter(s=>s.percent!==null),avg=measured.length?Math.round(measured.reduce((n,s)=>n+s.percent,0)/measured.length):null,target=measured.filter(s=>s.percent>=80).length,streaks=calculateStreaks(records),pc=records.reduce((n,d)=>n+score(d.priorities).done,0),mc=records.reduce((n,d)=>n+score(d.moves).done,0);const stats=[["Days tracked",records.length],["Average overall",avg===null?"Not measured":`${avg}%`],["80% days",`${target} (${measured.length?Math.round(target/measured.length*100):0}%)`],["Current streak",streaks.current],["Longest streak",streaks.longest],["Priorities completed",pc],["Small Moves completed",mc]],root=$("year-stats");root.replaceChildren();stats.forEach(([label,value])=>{const d=document.createElement("div"),s=document.createElement("strong"),l=document.createElement("span");d.className="stat";s.textContent=value;l.textContent=label;d.append(s,l);root.append(d);});const months=Array.from({length:12},(_,month)=>{const values=records.filter(d=>Number(d.date.slice(5,7))===month+1).map(d=>score([...d.priorities,...d.moves]).percent).filter(v=>v!==null);return{month,avg:values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length):null};}),best=months.filter(m=>m.avg!==null).sort((a,b)=>b.avg-a.avg)[0];if(best){const d=document.createElement("div"),s=document.createElement("strong"),l=document.createElement("span");d.className="stat";s.textContent=monthName(best.month);l.textContent=`Strongest month (${best.avg}%)`;d.append(s,l);root.append(d);}const bars=$("monthly-bars");bars.replaceChildren();months.forEach(m=>{const row=document.createElement("div"),label=document.createElement("span"),bar=document.createElement("span"),fill=document.createElement("span"),value=document.createElement("span");row.className="month-row";label.textContent=monthName(m.month,true);bar.className="bar";fill.style.width=`${m.avg||0}%`;bar.append(fill);value.textContent=m.avg===null?"—":`${m.avg}%`;row.append(label,bar,value);bars.append(row);});}
function calculateStreaks(records){const reached=new Set(records.filter(d=>score([...d.priorities,...d.moves]).percent>=80).map(d=>d.date));let longest=0,run=0;[...reached].sort().forEach((date,i,a)=>{run=i&&daysBetween(a[i-1],date)===1?run+1:1;longest=Math.max(longest,run);});let current=0,cursor=dateKey();while(reached.has(cursor)){current++;cursor=shiftDate(cursor,-1);}return{current,longest};}
function openHistoricalDay(date){activeDate=date;editable=false;showView("today");renderToday();scrollTo({top:0,behavior:"smooth"});}

async function exportJson(){const backup={app:"Minimal",version:VERSION,schemaVersion:SCHEMA_VERSION,exportedAt:new Date().toISOString(),profile:{name:config.name,initials:config.initials,locationLabel:config.locationLabel},settings:{accent:config.accent,milestoneEnabled:config.milestoneEnabled,reminder:config.reminder},config,days,statistics:exportStatistics()};download(`minimal-backup-${dateKey()}.json`,JSON.stringify(backup,null,2),"application/json");showToast("JSON backup downloaded.");}
function exportStatistics(){const result={};new Set(days.map(d=>d.date.slice(0,4))).forEach(year=>{const values=days.filter(d=>d.date.startsWith(year)).map(d=>score([...d.priorities,...d.moves]).percent).filter(v=>v!==null);result[year]={daysTracked:days.filter(d=>d.date.startsWith(year)).length,averageOverall:values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length):null,targetDays:values.filter(v=>v>=80).length};});return result;}
function exportReadable(){const configured=config.moves.map(m=>`${m.enabled===false?"[disabled]":"[enabled]"} ${m.label}`).join("; ")||"None";const mark=i=>validStatus(i.status)==="done"?"[done]":validStatus(i.status)==="skipped"?"[skipped]":"[pending]";const lines=[`MINIMAL ${VERSION} EXECUTION BACKUP — ${new Date().toLocaleString()}`,"",`LOCATION LABEL: ${config.locationLabel||"None"}`,`CURRENT SMALL MOVES: ${configured}`,"",...[...days].sort((a,b)=>b.date.localeCompare(a.date)).flatMap(d=>{const s=score([...d.priorities,...d.moves]);return[`${formatDate(d.date)} — ${s.percent===null?"Not measured":s.percent+"%"}`,`Priorities: ${d.priorities.map(p=>`${mark(p)} ${p.text}`).join("; ")||"None"}`,`Small Moves: ${d.moves.map(m=>`${m.enabled===false?"[disabled]":mark(m)} ${m.label}`).join("; ")||"None"}`,`Conclusion: ${d.conclusion||"—"}`,""];})];download(`minimal-readable-${dateKey()}.txt`,lines.join("\n"),"text/plain");}
async function importJson(e){const file=e.target.files?.[0];e.target.value="";if(!file)return;if(file.size>5*1024*1024)return showToast("Backup is too large (5 MB maximum).");try{const data=JSON.parse(await file.text()),schema=Number(data.schemaVersion??data.schema??1);if(data.app!=="Minimal"||![1,2,3].includes(schema)||!data.config||!Array.isArray(data.days))throw new Error();const sanitizedDays=data.days.map(sanitizeDay);if(sanitizedDays.some(d=>!d))throw new Error();const incomingConfig=sanitizeConfig(data.config),map=new Map(days.map(d=>[d.date,d]));let added=0,updated=0;sanitizedDays.forEach(d=>{const old=map.get(d.date);if(!old){map.set(d.date,d);added++;}else if((d.updatedAt||0)>(old.updatedAt||0)){map.set(d.date,d);updated++;}});days=[...map.values()];config=(incomingConfig.updatedAt||0)>(config.updatedAt||0)?incomingConfig:config;if(fallback)saveFallback();else{await idbPut("config",config);for(const d of days)await idbPut("days",d);}applyAccent();renderAll();await syncFocusTimer();showToast(`Import complete: ${added} added, ${updated} updated; duplicates skipped.`);}catch{showToast("Import rejected: malformed or unsupported Minimal backup.");}}
async function clearAll(){if($("clear-phrase").value!=="DELETE MINIMAL")return showToast("Confirmation phrase does not match.");if(db){db.close();await new Promise(resolve=>{const r=indexedDB.deleteDatabase(DB_NAME);r.onsuccess=r.onerror=r.onblocked=resolve;});db=null;}localStorage.removeItem("minimal.2.2.fallback");localStorage.removeItem("minimal.accent");config=defaultConfig();days=[];fallback=false;await openDatabase();await persistConfig();await ensureToday();$("clear-confirm").hidden=true;$("clear-phrase").value="";$("focus-layer").hidden=true;document.body.classList.remove("focus-open");activeDate=dateKey();renderAll();showToast("All Minimal data was permanently removed.");}
async function shareFeedback(){const value=text($("feedback").value,1000,true);if(!value)return showToast("Write feedback first.");const body=`Minimal ${VERSION}\n${value}`;try{if(navigator.share)await navigator.share({title:"Minimal feedback",text:body});else if(navigator.clipboard)await navigator.clipboard.writeText(body);else throw new Error();showToast(navigator.share?"Feedback shared by you.":"Feedback copied.");}catch(e){if(e.name!=="AbortError")showToast("Sharing is unavailable. Copy the text manually.");}}

function sanitizeFocusTimer(v){if(!v||typeof v!=="object"||!/^\d{4}-\d{2}-\d{2}$/.test(v.date)||!["priority","move","break"].includes(v.itemType))return null;const duration=clampInteger(v.duration,60,10800,1500),completed=Boolean(v.completed),running=!completed&&Boolean(v.running)&&Number.isFinite(Number(v.endAt));return{date:v.date,itemType:v.itemType,itemId:v.itemId?safeId(v.itemId,"item"):null,itemLabel:text(v.itemLabel,140)||"Focus session",duration,remaining:clampInteger(v.remaining,0,duration,duration),running,endAt:running?Number(v.endAt):null,completed,acknowledged:completed&&Boolean(v.acknowledged),sessionRecorded:Boolean(v.sessionRecorded),isBreak:v.itemType==="break"||Boolean(v.isBreak)};}
function sanitizeFocusSession(v,date){if(!v||typeof v!=="object"||!["priority","move"].includes(v.itemType))return null;const completed=new Date(v.completedAt);if(Number.isNaN(completed.getTime()))return null;return{id:safeId(v.id,"focus"),date,itemType:v.itemType,itemId:v.itemId?safeId(v.itemId,"item"):null,itemLabel:text(v.itemLabel,140)||"Focus session",plannedDuration:clampInteger(v.plannedDuration,60,10800,1500),completedAt:completed.toISOString()};}
function sanitizeConfig(v){if(!v||typeof v!=="object")return defaultConfig();const moves=Array.isArray(v.moves)?v.moves.slice(0,10).map((m,i)=>({id:safeId(m.id,"move"),label:text(m.label,80)||"Untitled Small Move",enabled:m.enabled!==false,order:i})):[];const launchers=Array.isArray(v.launchers)?v.launchers.slice(0,30).map((a,i)=>({id:safeId(a.id,"app"),name:text(a.name,40)||"App",url:normalizeUrl(a.url)||"https://example.com/",symbol:text(a.symbol,3),color:validColor(a.color)?a.color:"#9cffc8",pinned:Boolean(a.pinned),order:i})):DEFAULT_LAUNCHERS,reminder=v.reminder&&typeof v.reminder==="object"?v.reminder:{};return{key:"main",version:VERSION,name:text(v.name,40),initials:text(v.initials,3).toUpperCase(),locationLabel:text(v.locationLabel,40),accent:ACCENTS[v.accent]?v.accent:"mint",milestoneEnabled:v.milestoneEnabled!==false,reminder:{enabled:Boolean(reminder.enabled),time:/^([01]\d|2[0-3]):[0-5]\d$/.test(reminder.time)?reminder.time:"18:00"},focusTimer:sanitizeFocusTimer(v.focusTimer),moves,launchers,updatedAt:Number(v.updatedAt)||Date.now(),lastDate:/^\d{4}-\d{2}-\d{2}$/.test(v.lastDate)?v.lastDate:null,migrated:Boolean(v.migrated)};}
function sanitizeDay(v){if(!v||typeof v!=="object"||!/^\d{4}-\d{2}-\d{2}$/.test(v.date)||Number.isNaN(parseDate(v.date).getTime()))return null;const items=(list,max,labelKey)=>Array.isArray(list)?list.slice(0,max).map((x,i)=>({id:safeId(x.id,"item"),[labelKey]:text(x[labelKey],labelKey==="label"?80:140)||"Untitled",status:validStatus(x.status,x.done),order:i})):[];const moves=Array.isArray(v.moves)?v.moves.slice(0,10).map((m,i)=>({id:safeId(m.id,"move"),label:text(m.label,80)||"Untitled Small Move",status:validStatus(m.status,m.done),enabled:m.enabled!==false,order:i})):[],focusSessions=Array.isArray(v.focusSessions)?v.focusSessions.slice(0,1000).map(s=>sanitizeFocusSession(s,v.date)).filter(Boolean):[];return{date:v.date,priorities:items(v.priorities,10,"text"),planned:items(v.planned,10,"text"),moves,focusSessions,conclusion:text(v.conclusion,500,true),milestoneCelebrated:Boolean(v.milestoneCelebrated),reminderShown:Boolean(v.reminderShown),reminderDismissed:Boolean(v.reminderDismissed),rolloverResolved:["carry","archive","delete"].includes(v.rolloverResolved)?v.rolloverResolved:null,updatedAt:Number(v.updatedAt)||Date.now()};}
function normalizeUrl(raw){if(typeof raw!=="string"||!/^[a-z][a-z0-9+.-]*:/i.test(raw.trim()))return null;try{const u=new URL(raw.trim());if(!SAFE_PROTOCOLS.has(u.protocol)||u.protocol==="javascript:"||u.protocol==="data:")return null;if(u.protocol==="http:"&&!(["localhost","127.0.0.1"].includes(u.hostname)))return null;if(["https:","http:"].includes(u.protocol)&&(!u.hostname||u.username||u.password))return null;return u.href;}catch{return null;}}
function text(v,max,multiline=false){if(typeof v!=="string")return"";let s=v.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g,"");if(!multiline)s=s.replace(/\s+/g," ");return s.trim().slice(0,max);}
function clampInteger(value,min,max,fallback){const number=Number(value);return Number.isFinite(number)?Math.min(max,Math.max(min,Math.round(number))):fallback;}function validStatus(value,legacyDone=false){return["pending","done","skipped"].includes(value)?value:legacyDone?"done":"pending";}function validColor(v){return typeof v==="string"&&/^#[0-9a-f]{6}$/i.test(v);}function safeId(v,p){return typeof v==="string"&&/^[\w-]{1,100}$/.test(v)?v:uid(p);}function uid(p){return `${p}-${crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random().toString(16).slice(2)}`;}
function getDay(date){return days.find(d=>d.date===date);}function latestDayBefore(date){return days.filter(d=>d.date<date).sort((a,b)=>b.date.localeCompare(a.date))[0];}
function dateKey(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;}function parseDate(k){const [y,m,d]=k.split("-").map(Number);return new Date(y,m-1,d,12);}function shiftDate(k,n){const d=parseDate(k);d.setDate(d.getDate()+n);return dateKey(d);}function daysBetween(a,b){return Math.round((parseDate(b)-parseDate(a))/86400000);}function formatDate(k){return parseDate(k).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"});}function monthName(i,short=false){return new Date(2020,i,1).toLocaleDateString(undefined,{month:short?"short":"long"});}
function showView(name){if(name==="settings")editable=true;if(name==="today"&&activeDate!==dateKey())editable=false;document.querySelectorAll(".view").forEach(v=>{const active=v.id===`${name}-view`;v.hidden=!active;v.classList.toggle("active",active);});document.querySelectorAll(".bottom-nav [data-view]").forEach(b=>{const active=b.dataset.view===name;b.classList.toggle("active",active);b.setAttribute("aria-current",active?"page":"false");});if(name==="today"&&activeDate!==dateKey()&&!editable)renderToday();if(name==="history")renderHistory();location.hash=name;}
function tick(){const n=new Date();$("clock").textContent=n.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});if(dateKey()!==config?.lastDate)ensureToday().then(()=>{renderAll();checkReminder();});}function renderOnline(){const label=config?.locationLabel||"On-device";$("online-status").textContent=`${label} · ${navigator.onLine?"Online":"Offline"}`;}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement("a");a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500);}
function showToast(message,duration=3200){clearTimeout(toastTimer);$("toast").textContent=message;$("toast").hidden=false;toastTimer=setTimeout(()=>$("toast").hidden=true,duration);}
function registerServiceWorker(){if("serviceWorker" in navigator&&(location.protocol==="https:"||location.hostname==="localhost"||location.hostname==="127.0.0.1"))addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>showToast("Offline support could not start.")));}
